# nelmio_api_doc:
#     documentation:
#         info:
#             title: My App
#             description: This is an awesome app!
#             version: 1.0.0
#     areas: # to filter documented areas
#         path_patterns:
#             - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

nelmio_api_doc:
  documentation:
    info:
      title: TechnicalTest
      description: TechnicalTest app!
      version: 1.0.0
    paths:
      /:
        get:
          description: Endpoint HealthCheck to check the App availability
          tags:
            - Health check
          responses:
            200:
              description: OK
              content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        status: { type: string, example: 'ok' }
      # /api/post:
      #   post:
      #     description: Endpoint createPost
    tags:
      - name: Health check
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!(/doc|/doc.json)$) # Accepts routes under /api except /api/doc
